-- CreateEnum
CREATE TYPE "QuizType" AS ENUM ('MULTIPLE_CHOICE', 'IDENTIFICATION', 'ESSAY', 'COMPUTATIONAL', 'MIXED');

-- CreateEnum
CREATE TYPE "QuestionType" AS ENUM ('MULTIPLE_CHOICE', 'IDENTIFICATION', 'ESSAY', 'COMPUTATIONAL');

-- AlterTable
ALTER TABLE "Question" ADD COLUMN     "questionType" "QuestionType" NOT NULL DEFAULT 'MULTIPLE_CHOICE',
ALTER COLUMN "optionA" DROP NOT NULL,
ALTER COLUMN "optionB" DROP NOT NULL,
ALTER COLUMN "optionC" DROP NOT NULL,
ALTER COLUMN "optionD" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Quiz" ADD COLUMN     "avoidRepeatedQuestions" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "maxAttempts" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "questionsPerAttempt" INTEGER,
ADD COLUMN     "quizType" "QuizType" NOT NULL DEFAULT 'MULTIPLE_CHOICE',
ADD COLUMN     "shuffleOptions" BOOLEAN NOT NULL DEFAULT true;
